version: 2.1

orbs:
  slack: circleci/slack@4.13.1

executors:
  pnpm-executor:
    docker:
      - image: cimg/node:21.7-browsers

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Check node version
          command: node -v
      - run:
          name: Check pnpm version
          command: pnpm -v
      - run:
          name: Install packages
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Playground Build
          command: pnpm run dev:build
      - run:
          name: Module Build
          command: pnpm run build
      - run:
          name: Lint
          command: pnpm run lint
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context:
            - Slack
