version: 2.1

orbs:
  slack: circleci/slack@4.13.3

executors:
  pnpm-executor:
    docker:
      - image: cimg/node:22.2-browsers

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: pnpm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Module Build
          command: pnpm run build
      - run:
          name: Playground Build
          command: pnpm run dev:build
      - run:
          name: Docs Build
          command: pnpm run docs:build
      - run:
          name: YoastSEO example build
          command: pnpm run yoastseo:build
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context:
            - Slack
